Feature/scrum 6/authentification client mobile
csc-solutions/consumer-app pull request #1
Opened 2024-10-12 20:36 UTC by PacomeKFP

2024-10-13 09:06 UTC, dani-gouken requested changes

2024-10-13 09:06 UTC, dani-gouken commented on lib/backend/services/api_service.dart
> +    }).then((value) => {});
log le body du résultat

2024-10-13 09:06 UTC, dani-gouken commented on lib/backend/services/api_service.dart
> +    return _client.patch("/client", data: client.toJson()).then((res) => {});
log le body du résultat

2024-10-13 09:06 UTC, dani-gouken commented on lib/backend/services/client_service.dart
> +  /// Collecte les informations de l'appareil avec le package device_info_plus
le code source en anglais, donc les commentaire aussi

2024-10-13 09:06 UTC, dani-gouken commented on lib/main.dart
> +      await clientService.getSavedSessionToken(Config.getXClientSessionKey());
il ne faut pas await ici, sinon ça ralenti le lancement de l'app, laisse l'action se faire en arrière plan

2024-10-13 09:06 UTC, dani-gouken commented on lib/main.dart
> +  ApiService apiService = ApiService(clientService);
c'est préférable de retirer ceci ici et de faire ça quand l'application a plainement démarré.  initState du `FleetConsumerApp` (convertir en statefull widget si c'est pas déja le cas).  il faudra récupérer les services, via le context. je recommande aussi d'encapsuler la logique là dans une fonction. `initSession` par exemple

2024-10-13 12:37 UTC, PacomeKFP commented on lib/backend/services/api_service.dart
> +    }).then((value) => {});
Je ne comprend pas bien l'objectif ....

Pourquoi je devrait logger le body du resultat ? A quoi ça servirait ?

Je vais retirer le debugPrint là quand meme

2024-10-13 14:46 UTC, dani-gouken commented on lib/backend/services/api_service.dart
> +    }).then((value) => {});
sinon on a aucune indication que quelque chose c'est passé, même en dev. au moins logger un body avec un méssage

2024-10-14 13:09 UTC, dani-gouken requested changes

2024-10-14 13:09 UTC, dani-gouken commented on lib/screens/home/home_screen.dart
> +      final clientService = context.read<ClientService>();
tu peux abstraire tout ça dans le `ApiService`.
passe le `ClientService` dans le constructeur du`ApiService`
```dart
class ApiService {
  final ClientService clientService;
  ApiService(this.clientService);
}
```

2024-10-14 13:09 UTC, dani-gouken commented on lib/screens/home/home_screen.dart
> +      final results = await Future.wait([
je ne vois pas l'interet de faire un future.wait vue que la fonction est déja asynchrone

2024-10-14 13:09 UTC, dani-gouken commented on lib/backend/services/client_service.dart
> +  Future<String?> getSavedSessionToken(String sessionKey) async {
Techniquement cette fonction peux être synchrone. Tu peux passé une instance d'un `SharedPreference` Déja initialisé dans le constructeur de ceci.

Dans le main tu fait
```dart
var sharedPreferenceInstance = SharedPreference.getInstance
```
Ensuite tu garde ça dans les tu passe ça au service lors de ça création dans le `BlocProvider`

2024-10-14 13:09 UTC, dani-gouken commented on lib/screens/home/home_screen.dart
> +      sessionToken == null
c'est préférable d'abstraire ce check dans le service.
```dart
class ClientService {
// ....

bool get loggedIn => this.getSavedSession() != null;

Future void initSession() {
.....
this.loggedIn ? createSession() : updateSession();
} 
```

mieux: du peux creéer une fonction `upsertSession`qui prend les donnée et créer ou update en fonction du besoin

2024-10-14 13:09 UTC, dani-gouken commented on lib/screens/home/home_screen.dart
> +    } catch (err, trace) {
donc ici je m'attend à avoir un truc du style:
```dart
  Future<void> _initSession(BuildContext context) async {
     context.read<ClientService>.initSession();
  }
```

2024-10-17 13:43 UTC, dani-gouken approved these changes

2024-10-17 13:43 UTC, merged